create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null default '',
  event_date date,
  venue text not null default '',
  created_at timestamptz not null default now(),
  admin_name text not null default 'Admin Julieta',
  bank_name text not null default '',
  account_number text not null default ''
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  customer_id bigint not null references public.customers(id),
  description text not null,
  total_amount bigint not null check (total_amount > 0),
  paid_amount bigint not null default 0 check (paid_amount >= 0),
  due_date date not null,
  status text not null default 'Menunggu',
  created_at timestamptz not null default now(),
  admin_name text not null default 'Admin Julieta',
  service_type text not null default '',
  service_amount bigint not null default 0,
  location_zone text not null default '',
  location_fee bigint not null default 0,
  services_json jsonb not null default '[]'::jsonb
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id),
  amount bigint not null check (amount > 0),
  returned_amount bigint not null default 0 check (returned_amount >= 0),
  damaged_amount bigint not null default 0 check (damaged_amount >= 0),
  status text not null default 'Tersimpan',
  notes text not null default '',
  deposited_at timestamptz not null default now(),
  admin_name text not null default 'Admin Julieta'
);

create table if not exists public.deposit_damages (
  id bigint generated by default as identity primary key,
  deposit_id bigint not null references public.deposits(id) on delete cascade,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  replacement_cost bigint not null check (replacement_cost > 0),
  total_cost bigint not null check (total_cost > 0),
  admin_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.transaction_logs (
  id bigint generated by default as identity primary key,
  transaction_type text not null,
  reference_id bigint not null,
  admin_name text not null,
  details text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  setting_key text primary key,
  setting_value text not null
);

create table if not exists public.service_catalog (
  name text primary key,
  min_price bigint not null,
  max_price bigint not null,
  standard_price bigint not null
);

create table if not exists public.location_zones (
  name text primary key,
  fee bigint not null
);

insert into public.service_catalog (name, min_price, max_price, standard_price) values
  ('Event Organizer (Full Service)', 15000000, 25000000, 20000000),
  ('Decoration', 25000000, 65000000, 45000000),
  ('Make Up Artist (MUA)', 5000000, 9000000, 7000000),
  ('Wardrobe', 7500000, 18000000, 12750000),
  ('Catering (500 pax)', 45000000, 90000000, 67500000),
  ('Photobooth', 4000000, 7000000, 5500000),
  ('MC', 3500000, 7500000, 5500000),
  ('Penampilan Sanggar', 4500000, 9000000, 6750000)
on conflict (name) do update set
  min_price = excluded.min_price,
  max_price = excluded.max_price,
  standard_price = excluded.standard_price;

insert into public.location_zones (name, fee) values
  ('Zona 1 (Semarang & Sekitarnya)', 0),
  ('Zona 2 (Jateng & Jogja)', 2500000),
  ('Zona 3 (Destination Domestic - Jakarta/Bali)', 7500000),
  ('Zona 4 (ASEAN / International - SG, MY, Brunei)', 25000000)
on conflict (name) do update set fee = excluded.fee;

insert into public.app_settings (setting_key, setting_value)
values ('admin_name', 'Admin Julieta')
on conflict (setting_key) do nothing;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'customers', 'invoices', 'deposits', 'deposit_damages',
    'transaction_logs', 'app_settings', 'service_catalog', 'location_zones'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists authenticated_access on public.%I', table_name);
    execute format(
      'create policy authenticated_access on public.%I for select to authenticated using (true)',
      table_name
    );
    execute format('grant select on public.%I to authenticated', table_name);
    execute format('revoke insert, update, delete on public.%I from anon, authenticated', table_name);
  end loop;
end;
$$;

create or replace function public.create_customer(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved_customer public.customers;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
begin
  if length(regexp_replace(coalesce(p_payload->>'phone', ''), '[^0-9]', '', 'g')) < 8 then
    raise exception 'Nomor WhatsApp minimal 8 digit';
  end if;
  if nullif(trim(p_payload->>'bank_name'), '') is null
     or nullif(trim(p_payload->>'account_number'), '') is null then
    raise exception 'Nama bank dan nomor rekening wajib diisi';
  end if;

  insert into public.customers (name, phone, email, event_date, venue, created_at, admin_name, bank_name, account_number)
  values (
    trim(p_payload->>'name'), trim(p_payload->>'phone'), coalesce(p_payload->>'email', ''),
    nullif(p_payload->>'event_date', '')::date, coalesce(p_payload->>'venue', ''),
    coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now()),
    actor, trim(p_payload->>'bank_name'), trim(p_payload->>'account_number')
  ) returning * into saved_customer;

  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Pelanggan', saved_customer.id, actor, 'Tambah pelanggan ' || saved_customer.name, saved_customer.created_at);
  return to_jsonb(saved_customer);
end;
$$;

create or replace function public.update_customer(p_customer_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved_customer public.customers;
begin
  if length(regexp_replace(coalesce(p_payload->>'phone', ''), '[^0-9]', '', 'g')) < 8 then
    raise exception 'Nomor WhatsApp minimal 8 digit';
  end if;
  if nullif(trim(p_payload->>'bank_name'), '') is null
     or nullif(trim(p_payload->>'account_number'), '') is null then
    raise exception 'Nama bank dan nomor rekening wajib diisi';
  end if;

  update public.customers set
    name = trim(p_payload->>'name'), phone = trim(p_payload->>'phone'),
    email = coalesce(p_payload->>'email', ''), event_date = nullif(p_payload->>'event_date', '')::date,
    venue = coalesce(p_payload->>'venue', ''), bank_name = trim(p_payload->>'bank_name'),
    account_number = trim(p_payload->>'account_number')
  where id = p_customer_id returning * into saved_customer;
  if not found then raise exception 'Pelanggan tidak ditemukan'; end if;
  return to_jsonb(saved_customer);
end;
$$;

create or replace function public.create_invoice(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_count integer;
  found_count integer;
  service_total bigint;
  zone_fee bigint;
  paid bigint := coalesce(nullif(p_payload->>'paid_amount', '')::bigint, 0);
  services jsonb;
  service_names text;
  invoice_row public.invoices;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
  recorded_at timestamptz := coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now());
begin
  select count(*) into selected_count
  from (select distinct value from jsonb_array_elements_text(coalesce(p_payload->'service_types', '[]'::jsonb))) selected;
  select count(*), coalesce(sum(c.standard_price), 0),
         coalesce(jsonb_agg(jsonb_build_object('name', c.name, 'amount', c.standard_price) order by c.name), '[]'::jsonb),
         string_agg(c.name, ', ' order by c.name)
  into found_count, service_total, services, service_names
  from (select distinct value from jsonb_array_elements_text(coalesce(p_payload->'service_types', '[]'::jsonb))) selected
  join public.service_catalog c on c.name = selected.value;

  if selected_count = 0 or selected_count <> found_count then
    raise exception 'Pilih minimal satu jasa yang terdaftar';
  end if;
  select fee into zone_fee from public.location_zones where name = p_payload->>'location_zone';
  if not found then raise exception 'Pilih zona lokasi acara'; end if;
  if paid < 0 or paid > service_total + zone_fee then
    raise exception 'Nominal pembayaran awal tidak valid';
  end if;

  insert into public.invoices (
    invoice_number, customer_id, description, total_amount, paid_amount, due_date, status,
    created_at, admin_name, service_type, service_amount, location_zone, location_fee, services_json
  ) values (
    'INV-' || to_char(clock_timestamp(), 'YYMMDDHH24MISSMS'),
    (p_payload->>'customer_id')::bigint,
    coalesce(nullif(trim(p_payload->>'description'), ''), service_names),
    service_total + zone_fee, paid, (p_payload->>'due_date')::date,
    case when paid >= service_total + zone_fee then 'Lunas' when paid > 0 then 'Sebagian' else 'Menunggu' end,
    recorded_at, actor, service_names, service_total, p_payload->>'location_zone', zone_fee, services
  ) returning * into invoice_row;

  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Piutang', invoice_row.id, actor, 'Catat ' || invoice_row.invoice_number, recorded_at);
  return to_jsonb(invoice_row);
end;
$$;

create or replace function public.create_deposit(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  deposit_row public.deposits;
  amount_value bigint := (p_payload->>'amount')::bigint;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
  recorded_at timestamptz := coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now());
begin
  if amount_value <= 0 then raise exception 'Nominal deposit harus lebih dari nol'; end if;
  insert into public.deposits (customer_id, amount, notes, deposited_at, admin_name)
  values ((p_payload->>'customer_id')::bigint, amount_value, coalesce(p_payload->>'notes', ''), recorded_at, actor)
  returning * into deposit_row;
  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Deposit', deposit_row.id, actor, 'Setor deposit sebesar Rp' || amount_value, recorded_at);
  return to_jsonb(deposit_row);
end;
$$;

create or replace function public.record_payment(p_invoice_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  invoice_row public.invoices;
  amount_value bigint := (p_payload->>'paid_amount')::bigint;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
  recorded_at timestamptz := coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now());
begin
  select * into invoice_row from public.invoices where id = p_invoice_id for update;
  if not found or amount_value <= 0 or invoice_row.paid_amount + amount_value > invoice_row.total_amount then
    raise exception 'Pembayaran tidak valid atau melebihi sisa tagihan';
  end if;
  update public.invoices set paid_amount = paid_amount + amount_value,
    status = case when paid_amount + amount_value >= total_amount then 'Lunas' else 'Sebagian' end,
    admin_name = actor
  where id = p_invoice_id returning * into invoice_row;
  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Penagihan', p_invoice_id, actor, 'Pembayaran ' || invoice_row.invoice_number || ' sebesar Rp' || amount_value, recorded_at);
  return to_jsonb(invoice_row);
end;
$$;

create or replace function public.record_damage(p_deposit_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  deposit_row public.deposits;
  quantity_value integer := (p_payload->>'quantity')::integer;
  unit_cost bigint := (p_payload->>'replacement_cost')::bigint;
  total_value bigint;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
  recorded_at timestamptz := coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now());
begin
  select * into deposit_row from public.deposits where id = p_deposit_id for update;
  total_value := quantity_value::bigint * unit_cost;
  if not found or quantity_value <= 0 or unit_cost <= 0
     or deposit_row.returned_amount + deposit_row.damaged_amount + total_value > deposit_row.amount then
    raise exception 'Potongan kerusakan melebihi sisa deposit';
  end if;
  insert into public.deposit_damages (deposit_id, item_name, quantity, replacement_cost, total_cost, admin_name, created_at)
  values (p_deposit_id, trim(p_payload->>'item_name'), quantity_value, unit_cost, total_value, actor, recorded_at);
  update public.deposits set damaged_amount = damaged_amount + total_value,
    status = 'Dipotong Kerusakan', admin_name = actor
  where id = p_deposit_id returning * into deposit_row;
  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Potongan kerusakan', p_deposit_id, actor, trim(p_payload->>'item_name') || ' x' || quantity_value || ', potongan Rp' || total_value, recorded_at);
  return to_jsonb(deposit_row);
end;
$$;

create or replace function public.return_deposit(p_deposit_id bigint, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  deposit_row public.deposits;
  amount_value bigint := (p_payload->>'returned_amount')::bigint;
  remaining bigint;
  actor text := coalesce(nullif(left(trim(p_payload->>'admin_name'), 80), ''), 'Admin Julieta');
  recorded_at timestamptz := coalesce(nullif(p_payload->>'recorded_at', '')::date + localtime, now());
begin
  select * into deposit_row from public.deposits where id = p_deposit_id for update;
  if not found or amount_value <= 0
     or deposit_row.returned_amount + deposit_row.damaged_amount + amount_value > deposit_row.amount then
    raise exception 'Nominal pengembalian melebihi sisa deposit';
  end if;
  remaining := deposit_row.amount - deposit_row.returned_amount - deposit_row.damaged_amount - amount_value;
  update public.deposits set returned_amount = returned_amount + amount_value,
    status = case
      when remaining = 0 and damaged_amount = 0 then 'Dikembalikan'
      when damaged_amount > 0 then 'Dipotong Kerusakan'
      else 'Dikembalikan Sebagian'
    end,
    admin_name = actor
  where id = p_deposit_id returning * into deposit_row;
  insert into public.transaction_logs (transaction_type, reference_id, admin_name, details, created_at)
  values ('Pengembalian deposit', p_deposit_id, actor, 'Pengembalian sebesar Rp' || amount_value, recorded_at);
  return to_jsonb(deposit_row);
end;
$$;

create or replace function public.set_admin_name(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor text := nullif(left(trim(p_payload->>'admin_name'), 80), '');
begin
  if actor is null then raise exception 'Nama admin wajib diisi'; end if;
  insert into public.app_settings (setting_key, setting_value)
  values ('admin_name', actor)
  on conflict (setting_key) do update set setting_value = excluded.setting_value;
  return jsonb_build_object('admin_name', actor);
end;
$$;

create or replace function public.delete_invoice(p_invoice_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.invoices where id = p_invoice_id) then
    raise exception 'Piutang tidak ditemukan';
  end if;
  delete from public.transaction_logs
  where reference_id = p_invoice_id and transaction_type in ('Piutang', 'Penagihan');
  delete from public.invoices where id = p_invoice_id;
  return jsonb_build_object('id', p_invoice_id);
end;
$$;

create or replace function public.delete_deposit(p_deposit_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.deposits where id = p_deposit_id) then
    raise exception 'Deposit tidak ditemukan';
  end if;
  delete from public.transaction_logs
  where reference_id = p_deposit_id and transaction_type in ('Deposit', 'Potongan kerusakan', 'Pengembalian deposit');
  delete from public.deposits where id = p_deposit_id;
  return jsonb_build_object('id', p_deposit_id);
end;
$$;

create or replace function public.delete_customer(p_customer_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.customers where id = p_customer_id) then
    raise exception 'Pelanggan tidak ditemukan';
  end if;
  delete from public.transaction_logs
  where (transaction_type = 'Pelanggan' and reference_id = p_customer_id)
     or (transaction_type in ('Piutang', 'Penagihan') and reference_id in (select id from public.invoices where customer_id = p_customer_id))
     or (transaction_type in ('Deposit', 'Potongan kerusakan', 'Pengembalian deposit') and reference_id in (select id from public.deposits where customer_id = p_customer_id));
  delete from public.deposits where customer_id = p_customer_id;
  delete from public.invoices where customer_id = p_customer_id;
  delete from public.customers where id = p_customer_id;
  return jsonb_build_object('id', p_customer_id);
end;
$$;

revoke all on function public.create_customer(jsonb) from public, anon;
revoke all on function public.update_customer(bigint, jsonb) from public, anon;
revoke all on function public.create_invoice(jsonb) from public, anon;
revoke all on function public.create_deposit(jsonb) from public, anon;
revoke all on function public.record_payment(bigint, jsonb) from public, anon;
revoke all on function public.record_damage(bigint, jsonb) from public, anon;
revoke all on function public.return_deposit(bigint, jsonb) from public, anon;
revoke all on function public.set_admin_name(jsonb) from public, anon;
revoke all on function public.delete_invoice(bigint) from public, anon;
revoke all on function public.delete_deposit(bigint) from public, anon;
revoke all on function public.delete_customer(bigint) from public, anon;
grant execute on function public.create_customer(jsonb) to authenticated;
grant execute on function public.update_customer(bigint, jsonb) to authenticated;
grant execute on function public.create_invoice(jsonb) to authenticated;
grant execute on function public.create_deposit(jsonb) to authenticated;
grant execute on function public.record_payment(bigint, jsonb) to authenticated;
grant execute on function public.record_damage(bigint, jsonb) to authenticated;
grant execute on function public.return_deposit(bigint, jsonb) to authenticated;
grant execute on function public.set_admin_name(jsonb) to authenticated;
grant execute on function public.delete_invoice(bigint) to authenticated;
grant execute on function public.delete_deposit(bigint) to authenticated;
grant execute on function public.delete_customer(bigint) to authenticated;

notify pgrst, 'reload schema';
